'use client';
import { useEffect,useState } from 'react';
import { ArrowDownToLine,ArrowRight,Clapperboard,Images,ScanFace,ShieldCheck,Film,Check,Save,Copy,Sparkles } from 'lucide-react';
import type { Analysis,Consistency,Shot,Workflow } from '@/types/workflow';
import { consistencyLabels,createWorkflow,generateShots,isWorkflow,timeRanges,totalDuration } from '@/lib/workflow';
import { exportDocument,exportJson,exportPrompts } from '@/lib/export';
import ImageUpload from './ImageUpload';
import AnalysisEditor from './AnalysisEditor';
import ShotEditor from './ShotEditor';
const STORAGE_KEY='fashion-video-studio-draft-v1';
export default function Studio(){
 const [workflow,setWorkflow]=useState<Workflow>(createWorkflow),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[references,setReferences]=useState({clothing:false,person:false}),[provider,setProvider]=useState('kling');
 useEffect(()=>{try{const stored=localStorage.getItem(STORAGE_KEY);if(stored){const parsed:unknown=JSON.parse(stored);if(isWorkflow(parsed)){setWorkflow(parsed);setMessage('已恢复本地文字草稿；参考图片需重新上传。');}}}catch{setMessage('无法读取本地草稿，仍可正常创作与导出。');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(workflow));}catch{/* 手动保存按钮提供错误反馈 */}},[workflow,ready]);
 function updateAnalysis(analysis:Analysis){setWorkflow(w=>({...w,analysis,analysisStatus:'manual'}));}
 function updateShot(shot:Shot){setWorkflow(w=>({...w,shots:w.shots.map(s=>s.id===shot.id?shot:s)}));}
 function regenerate(){setWorkflow(w=>({...w,shots:generateShots(w.analysis,w.consistency)}));setMessage('已按当前设定重新生成五分镜模板；未执行图片识别或视频生成。');}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage('提示词已复制。');}catch{setMessage('浏览器未允许剪贴板访问，请选中文字手动复制，或导出 TXT。');}}
 function download(format:'json'|'txt'|'md'){
  if(totalDuration(workflow.shots)!==15){setMessage('请先将五个镜头的总时长调整为 15 秒，再导出方案。');return;}
  const text=format==='json'?exportJson(workflow):format==='txt'?exportPrompts(workflow):exportDocument(workflow);
  const url=URL.createObjectURL(new Blob([format==='json'?text:'\uFEFF'+text],{type:format==='json'?'application/json;charset=utf-8':'text/plain;charset=utf-8'}));
  const anchor=document.createElement('a');anchor.href=url;anchor.download=`Fashion-Video-Studio.${format}`;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('方案已导出；当前未生成视频文件。');
 }
 function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(workflow));setMessage('文字草稿已保存在当前浏览器，参考图片不会持久保存。');}catch{setMessage('浏览器存储不可用，请导出方案备份。');}}
 const ranges=timeRanges(workflow.shots),duration=totalDuration(workflow.shots),analysisStatus=workflow.analysisStatus==='pending'?'待分析':workflow.analysisStatus==='manual'?'手动编辑':'AI 分析';
 const nav=[['references','参考素材',Images],['analysis','结构化分析',ScanFace],['consistency','画面一致性',ShieldCheck],['storyboard','五镜头规划',Clapperboard],['export','导出与服务',Film]] as const;
 return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 hidden w-56 border-r border-[#e4e8dd] bg-white px-6 py-9 lg:block"><a href="#" className="block"><span className="text-2xl font-semibold tracking-tight">Fashion<span className="text-[#8f9e7b]">.</span></span><span className="mt-1 block text-[10px] tracking-[3px] text-[#89967b]">VIDEO STUDIO</span></a><p className="mb-5 mt-14 text-[10px] tracking-widest text-[#a0aa95]">创作工作台</p><nav className="space-y-2">{nav.map(([id,label,Icon],i)=><a key={id} href={`#${id}`} className={`flex items-center gap-3 rounded-md px-3 py-3 text-xs ${i===0?'bg-[#eef3e7] text-[#536d40]':'text-[#819075] hover:bg-[#f6f8f2]'}`}><Icon size={16}/>{label}</a>)}</nav><div className="absolute bottom-8 text-[10px] text-[#8c9b7e]"><span className="mr-2 inline-block size-1.5 rounded-full bg-[#96ac7a]"/>第一阶段 · 策划工作流<p className="mt-3 tracking-widest">FASHION IN MOTION</p></div></aside>
 <main className="mx-auto max-w-[1750px] px-5 pb-8 lg:ml-56 lg:px-10"><header className="flex h-20 items-center justify-between border-b border-[#e1e6da]"><div className="text-xs text-[#8a947f]"><span className="hidden sm:inline">Fashion Video Studio <span className="mx-3 text-[#bdc5b2]">/</span></span>女装视频工作流</div><button className="btn" onClick={save}><Save size={14}/>保存草稿</button></header>
 <section className="flex items-end justify-between gap-6 py-9"><div><p className="eyebrow mb-4">FROM REFERENCE TO FASHION STORY</p><h1 className="text-2xl font-semibold tracking-wide md:text-3xl">让每一件女装，有自己的故事<span className="text-[#97a580]">。</span></h1><p className="mt-4 text-xs leading-6 text-[#8b967e]">整理你的参考素材与创作设定，构建一份连贯、可执行的 15 秒视频方案。</p></div><div className="hidden text-right md:block"><span className="text-4xl font-light text-[#b5c1a4]">15<span className="ml-1 text-sm">s</span></span><p className="mt-1 text-[10px] tracking-widest text-[#92a17e]">9:16 / 5 SHOTS</p></div></section>
 <div className="mb-7 flex flex-wrap items-center gap-3 text-[11px] text-[#95a287]">{['上传参考','整理设定','保持一致','规划分镜','导出方案'].map((s,i)=><span key={s} className="flex items-center gap-3"><span className={i===0?'text-[#4f6b3c]':''}>{String(i+1).padStart(2,'0')} {s}</span>{i<4&&<ArrowRight size={12} className="text-[#c0cab3]"/>}</span>)}</div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-6"><section id="references" className="panel"><div className="flex items-center justify-between"><h2 className="section-title">参考素材</h2><span className="eyebrow">REFERENCE</span></div><p className="muted mt-2 mb-6">分别上传商品与人物照片，为整段视频建立统一视觉依据。</p><div className="grid gap-6 md:grid-cols-2"><ImageUpload kind="clothing" title="服装参考图" subtitle="连衣裙、上衣等清晰商品照片" onChange={present=>setReferences(r=>({...r,clothing:present}))}/><ImageUpload kind="person" title="人物参考图" subtitle="建议使用清晰的模特正面脸部照片" onChange={present=>setReferences(r=>({...r,person:present}))}/></div><p className="mt-4 border-t border-[#edf0e7] pt-4 text-[11px] text-[#98a28c]">图片仅在当前页面本地预览，不会发送到外部服务；刷新后需要重新上传。</p></section>
 <section id="analysis" className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">结构化分析</h2><span className="rounded-full bg-[#f3f0e5] px-3 py-1 text-[10px] text-[#998954]">{analysisStatus}</span></div><div className="mt-4 rounded-md border border-[#e7e9da] bg-[#f9faf2] p-3 text-xs leading-6 text-[#8d957d]">视觉模型尚未接入，上传图片不会自动识别。请根据参考图手动填写，所有字段均可编辑；未填写项保持待分析。</div><AnalysisEditor value={workflow.analysis} onChange={updateAnalysis}/></section>
 <section id="consistency" className="panel"><div className="flex items-center justify-between"><h2 className="section-title">画面一致性</h2><span className="eyebrow">VISUAL CONSISTENCY</span></div><p className="muted mt-2">这些约束将写入重新生成的中英文提示词，供未来视频模型使用。</p><div className="mt-5 grid gap-4 md:grid-cols-2">{Object.entries(consistencyLabels).map(([key,label])=><label className="flex cursor-pointer items-start gap-3 rounded-md border border-[#e4e9dc] bg-[#fbfcf8] p-3 text-xs leading-6 text-[#657757]" key={key}><input className="mt-1 accent-[#63844a]" type="checkbox" checked={workflow.consistency[key as keyof Consistency]} onChange={e=>setWorkflow(w=>({...w,consistency:{...w.consistency,[key]:e.target.checked}}))}/>{label}</label>)}</div></section>
 <section id="storyboard" className="panel"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="section-title">五镜头规划</h2><p className="muted mt-2">默认 15 秒 · 9:16 · 模板方案，不是真实生成结果</p></div><button className="btn btn-primary" onClick={regenerate}><Sparkles size={14}/>按当前设定重新生成</button></div><p className="mt-3 text-[11px] leading-6 text-[#9aa48d]">重新生成会覆盖当前镜头编辑；人物、服装与场景设定会保留。英文为可编辑模板，中文自定义设定不会自动翻译。</p><div className="my-5 flex gap-1.5" aria-label="分镜时间轴">{workflow.shots.map((s,i)=><div key={s.id} style={{flex:s.duration}} className="min-w-0 rounded-md bg-[#eaf0df] px-2 py-3 text-center"><p className="truncate text-[10px] text-[#68824f]">{s.name}</p><p className="mt-1 text-[9px] text-[#91a37b]">{ranges[i]}</p></div>)}</div>{duration!==15&&<p role="alert" className="mb-5 rounded-md bg-amber-50 p-3 text-xs text-amber-800">当前总时长 {duration} 秒，请调整为 15 秒后导出。</p>}<div className="space-y-4">{workflow.shots.map((shot,i)=><ShotEditor key={shot.id} shot={shot} range={ranges[i]} onChange={updateShot} onCopy={text=>void copy(text)}/>)}</div></section>
 <section id="export" className="panel"><h2 className="section-title">导出与视频服务</h2><p className="muted mt-2">先完成创作方案，再将提示词交给你选择的视频生成平台。</p><div className="mt-5 flex flex-wrap gap-3"><button className="btn" onClick={()=>download('json')}><ArrowDownToLine size={14}/>完整分镜 JSON</button><button className="btn" onClick={()=>download('txt')}><ArrowDownToLine size={14}/>中英文提示词 TXT</button><button className="btn" onClick={()=>download('md')}><ArrowDownToLine size={14}/>分镜规划文档</button><button className="btn" onClick={()=>void copy(exportPrompts(workflow))}><Copy size={14}/>复制全部提示词</button></div><div className="mt-6 flex flex-wrap items-center gap-4 rounded-lg border border-[#e5e9de] bg-[#fafbf6] p-4"><Film size={20} className="text-[#8c9f76]"/><label className="flex items-center gap-3 text-xs text-[#778769]">未来视频服务<select className="field !w-36" value={provider} onChange={e=>setProvider(e.target.value)}><option value="kling">可灵</option><option value="jimeng">即梦</option><option value="sora">Sora</option><option value="custom">其他服务</option></select></label><button className="btn" disabled>视频生成 · 尚未接入</button><p className="w-full text-[11px] text-[#97a48a]">已预留统一任务 API 与适配器。不需要 API Key，不创建模拟成功任务，MP4 合成留待真实服务接入。</p></div></section></div>
 <aside className="hidden xl:block"><div className="sticky top-6 space-y-5"><section className="panel !p-5"><p className="eyebrow mb-4">PROJECT OVERVIEW</p><label className="block text-xs text-[#7c8c6c]">项目名称<input aria-label="项目名称" className="field mt-2" value={workflow.name} onChange={e=>setWorkflow(w=>({...w,name:e.target.value}))}/></label><div className="my-5 grid grid-cols-3 border-y border-[#e7ebdf] py-4 text-center">{[['15s','目标时长'],['9:16','竖屏画幅'],['05','视频镜头']].map(([n,l])=><div key={l}><p className="text-xl font-light text-[#728963]">{n}</p><p className="mt-1 text-[9px] text-[#99a58d]">{l}</p></div>)}</div><div className="space-y-3 text-xs text-[#819273]">{[['服装参考',references.clothing],['人物参考',references.person],['人物 / 服装 / 场景',workflow.analysisStatus!=='pending']].map(([label,done])=><div className="flex items-center justify-between" key={String(label)}><span>{label}</span>{done?<Check size={14} className="text-[#6d8c50]"/>:<span className="text-[10px] text-[#acb39f]">待完善</span>}</div>)}</div><p className="mt-5 border-t border-[#e7ebdf] pt-4 text-[11px] leading-6 text-[#9ba58e]">当前为策划工作流。草稿文字自动保存在本浏览器，图片仅供本次预览。</p></section><div className="rounded-lg bg-[#ecf1e4] p-5"><p className="text-xs font-medium text-[#71825e]">一个角色，一件服装，一段故事。</p><p className="mt-3 text-[11px] leading-6 text-[#98a589]">先确认细节，再开始生成，让每个镜头都延续同一种视觉语言。</p></div></div></aside></div>
 <footer className="mt-7 flex justify-between text-[10px] text-[#a0aa95]"><span>FASHION VIDEO STUDIO</span><span>从静态灵感，到动态表达。</span></footer></main>{message&&<div role="status" className="fixed right-5 bottom-5 z-50 flex max-w-lg items-start gap-4 rounded-lg border border-[#d5dfc9] bg-white px-5 py-4 text-xs leading-6 text-[#667e50] shadow-lg"><span>{message}</span><button aria-label="关闭消息" onClick={()=>setMessage('')} className="text-[#9ba58e]">×</button></div>}</div>;
}
